repos:
- hooks:
  - id: black
  repo: https://github.com/python/black
  rev: 22.3.0
- hooks:
  - id: zimports
  repo: https://github.com/sqlalchemyorg/zimports
  rev: v0.5.0
- hooks:
  - additional_dependencies:
    - flake8-import-order
    - flake8-builtins
    - flake8-future-annotations
    - flake8-docstrings>=1.6.0
    - flake8-rst-docstrings
    - pydocstyle
    - pygments
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 4.0.1
